version: '3'
services:
  truffle-scanner:
    image: truffle-scanner:latest
    container_name: truffle-scanner
    build:
      context: .
      dockerfile: infrastructure/Dockerfile
    volumes:
      - ./clones:/home/scanner
    env_file:
      - .env
    networks:
      - scanner-net

networks:
  scanner-net:
    driver: bridge
