version: '3.7'
services:

  build-env:
    image: golang:1.21-alpine3.18
    environment:
      - GO111MODULE=on
      - GOSUMDB=off
    platform: linux/amd64
    volumes:
      - type: volume
        source: truffle_scanner_dep
        target: /go
      - type: bind
        source: ../
        target: /truffle-scanner
    working_dir: /truffle-scanner

volumes:
  truffle_scanner_dep:
